name: Build Project

on:
  push:
    branches:
      - master  # Default branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Initialize submodules
      - name: Initialize submodules
        run: |
          git submodule update --init --recursive

      # Step 3: Set up Clang
      - name: Set up Clang
        run: sudo apt-get install -y clang

      # Step 4: Build the project using Makefile
      - name: Build the project
        run: |
          make

      # Step 5: Create and upload release using softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')  # Only trigger on tag push
        with:
          files: build/usr/bin/shortcut-sign  # Adjust this to point to your built binary
          tag_name: "v$(date +'%Y%m%d%H%M%S')"  # Use a timestamp as version tag (you can change it to your own versioning scheme)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is set to push releases
